export enum BranchBankAccountPurpose {
  REPAYMENT_COLLECTION = 'REPAYMENT_COLLECTION',
  DISBURSEMENT_SOURCE = 'DISBURSEMENT_SOURCE',
  GENERAL = 'GENERAL',
}

export enum BranchFundingStatus {
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum BranchFundingSource {
  HEAD_OFFICE = 'HEAD_OFFICE',
}
